"""
scheduler.py — Windows Task Scheduler command/XML generator.

Produces schtasks.exe commands and a PowerShell alternative
that the user can paste into a terminal to register the backup job.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Optional

from models import Frequency, JobConfig


# ---------------------------------------------------------------------------
# schtasks command builder
# ---------------------------------------------------------------------------

def _quote_win(s: str) -> str:
    """Escape a Windows path for use inside double-quoted schtasks arguments."""
    return str(s).replace('"', '\\"')


def build_task_command(config: JobConfig, output_folder: Path) -> str:
    """
    Build the full content of the _task.txt artifact file.
    Includes both an schtasks.exe one-liner and a PowerShell equivalent.
    """
    bat_path = output_folder / f"backup_{config.job_name}.bat"
    sched    = config.scheduler

    lines = [
        f"# Task Scheduler commands for job: {config.job_name}",
        f"# Generated by rclone Backup Configurator.",
        "",
        "## OPTION A — schtasks.exe (run in an elevated Command Prompt or PowerShell)",
        "",
    ]

    lines.append(_build_schtasks_cmd(config, bat_path))
    lines += [
        "",
        "## OPTION B — PowerShell (recommended for paths with spaces)",
        "",
    ]
    lines.append(_build_powershell_cmd(config, bat_path))
    lines += [
        "",
        "## Notes",
        f"# Schedule file to run: {bat_path}",
        f"# Frequency: {sched.frequency.value}",
    ]
    if sched.frequency != Frequency.MANUAL:
        lines.append(f"# Trigger time: {sched.trigger_time}")
    if sched.frequency == Frequency.WEEKLY:
        lines.append(f"# Day of week: {sched.day_of_week}")

    return "\n".join(lines) + "\n"


def _build_schtasks_cmd(config: JobConfig, bat_path: Path) -> str:
    sched = config.scheduler
    freq  = sched.frequency

    task_name = f"RcloneBackup_{config.job_name}"
    cmd = (
        f'schtasks /Create /TN "{task_name}" '
        f'/TR "cmd /c \\"{_quote_win(bat_path)}\\"" '
        f'/F '   # overwrite if exists
    )

    if freq == Frequency.HOURLY:
        cmd += "/SC HOURLY"
    elif freq == Frequency.DAILY:
        cmd += f"/SC DAILY /ST {sched.trigger_time}"
    elif freq == Frequency.WEEKLY:
        cmd += f"/SC WEEKLY /D {sched.day_of_week[:3].upper()} /ST {sched.trigger_time}"
    else:
        cmd += "/SC ONCE /ST 00:00"  # manual — user must trigger manually

    # Run hidden and with lowest practical privilege escalation
    cmd += " /RL HIGHEST /RU SYSTEM"
    return cmd


def _build_powershell_cmd(config: JobConfig, bat_path: Path) -> str:
    sched = config.scheduler
    freq  = sched.frequency
    task_name = f"RcloneBackup_{config.job_name}"

    trigger_build = {
        Frequency.HOURLY:  "New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Hours 1) -Once -At '00:00'",
        Frequency.DAILY:   f"New-ScheduledTaskTrigger -Daily -At '{sched.trigger_time}'",
        Frequency.WEEKLY:  f"New-ScheduledTaskTrigger -Weekly -DaysOfWeek {sched.day_of_week} -At '{sched.trigger_time}'",
        Frequency.MANUAL:  "New-ScheduledTaskTrigger -Once -At '00:00'  # Manual: remove trigger after creation",
    }
    trigger = trigger_build.get(freq, trigger_build[Frequency.MANUAL])

    ps = (
        f"$action  = New-ScheduledTaskAction -Execute 'cmd.exe' "
        f"-Argument '/c \"{_quote_win(bat_path)}\"'\n"
        f"$trigger = {trigger}\n"
        f"$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Hours 12) "
        f"-MultipleInstances IgnoreNew -Hidden\n"
        f"Register-ScheduledTask -TaskName '{task_name}' "
        f"-Action $action -Trigger $trigger -Settings $settings "
        f"-RunLevel Highest -Force"
    )
    return ps
