"""
templates.py — Runtime backup script template for rclone Backup Configurator.

Renders a standalone Python script with:
  - preflight checks (rclone exists, source/log folders exist)
  - lock file protection with stale-lock timeout
  - configurable retry loop
  - rclone copy with all flags from JobConfig
  - optional post-copy rclone check
  - JSON status artifact output
  - timestamped log file
"""
from __future__ import annotations

# The generated script is embedded as a string template.
# Keys in {curly braces} are replaced by generator.py via str.format_map().

RUNTIME_TEMPLATE = '''\
#!/usr/bin/env python3
"""
Backup script: {job_name}
Generated by rclone Backup Configurator.
DO NOT EDIT — re-generate from the configurator if changes are needed.
"""
from __future__ import annotations

import json
import logging
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration (injected by generator)
# ---------------------------------------------------------------------------
JOB_NAME          = {job_name_repr}
SOURCE_FOLDERS    = {source_folders_repr}   # list[str]
RCLONE_DEST       = {rclone_dest_repr}      # "remote:path"
LOG_FOLDER        = Path({log_folder_repr})
BACKUP_MODE       = {backup_mode_repr}      # "copy" | "dry_run" | "check_only"
RCLONE_EXE        = {rclone_exe_repr}       # "rclone" or absolute path

RETRIES           = {retries}
LOW_LEVEL_RETRIES = {low_level_retries}
CHECKERS          = {checkers}
TRANSFERS         = {transfers}
LOG_LEVEL         = {log_level_repr}
BWLIMIT           = {bwlimit_repr}          # "" = no limit
CHECKSUM          = {checksum}
EXCLUDE_PATTERNS  = {exclude_patterns_repr} # list[str]
EXCLUDE_FROM      = {exclude_from_repr}     # "" = not set

POST_VALIDATION   = {post_copy_validation}
LOCK_TIMEOUT_SEC  = {lock_timeout_seconds}
RETRY_DELAY_SEC   = {retry_delay_seconds}

LOCK_FILE         = LOG_FOLDER / f"{{JOB_NAME}}.lock"
STATUS_FILE       = LOG_FOLDER / f"{{JOB_NAME}}_last_run_status.json"

# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------
def _setup_logging(log_file: Path) -> logging.Logger:
    fmt = "%(asctime)s %(levelname)-8s %(message)s"
    logging.basicConfig(
        level=getattr(logging, LOG_LEVEL, logging.INFO),
        format=fmt,
        handlers=[
            logging.FileHandler(log_file, encoding="utf-8"),
            logging.StreamHandler(sys.stdout),
        ],
    )
    return logging.getLogger("backup")


# ---------------------------------------------------------------------------
# Lock helpers
# ---------------------------------------------------------------------------
def _acquire_lock(logger: logging.Logger) -> bool:
    """Write PID to lock file. Return True if acquired, False if another instance holds it."""
    if LOCK_FILE.exists():
        try:
            pid = int(LOCK_FILE.read_text().strip())
            age = time.time() - LOCK_FILE.stat().st_mtime
            # Check if the process is actually alive
            try:
                os.kill(pid, 0)
                alive = True
            except (OSError, ProcessLookupError):
                alive = False

            if alive and age < LOCK_TIMEOUT_SEC:
                logger.error("Another backup instance is running (PID %d, age %.0fs).", pid, age)
                return False
            else:
                logger.warning("Stale lock found (PID %d, age %.0fs). Removing.", pid, age)
                LOCK_FILE.unlink(missing_ok=True)
        except ValueError:
            logger.warning("Corrupt lock file. Removing.")
            LOCK_FILE.unlink(missing_ok=True)

    LOCK_FILE.write_text(str(os.getpid()))
    return True


def _release_lock() -> None:
    LOCK_FILE.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Preflight checks
# ---------------------------------------------------------------------------
def _preflight(logger: logging.Logger) -> list[str]:
    """Return list of preflight failure messages. Empty = all OK."""
    failures = []

    import shutil
    if not shutil.which(RCLONE_EXE) and not Path(RCLONE_EXE).is_file():
        failures.append(f"rclone not found: {{RCLONE_EXE}}")

    for src in SOURCE_FOLDERS:
        p = Path(src)
        if not p.exists():
            failures.append(f"Source folder missing: {{p}}")
        elif not p.is_dir():
            failures.append(f"Source path is not a directory: {{p}}")

    LOG_FOLDER.mkdir(parents=True, exist_ok=True)
    return failures


# ---------------------------------------------------------------------------
# rclone command builder
# ---------------------------------------------------------------------------
def _build_rclone_cmd(source: str, dest: str, dry_run: bool = False) -> list[str]:
    cmd = [RCLONE_EXE]

    if BACKUP_MODE == "check_only":
        cmd.append("check")
    else:
        cmd.append("copy")

    cmd += [source, dest]

    cmd += [
        f"--retries={{RETRIES}}",
        f"--low-level-retries={{LOW_LEVEL_RETRIES}}",
        f"--checkers={{CHECKERS}}",
        f"--transfers={{TRANSFERS}}",
        f"--log-level={{LOG_LEVEL}}",
    ]

    if dry_run or BACKUP_MODE == "dry_run":
        cmd.append("--dry-run")

    if CHECKSUM:
        cmd.append("--checksum")

    if BWLIMIT:
        cmd += ["--bwlimit", BWLIMIT]

    for pattern in EXCLUDE_PATTERNS:
        cmd += ["--exclude", pattern]

    if EXCLUDE_FROM:
        cmd += ["--exclude-from", EXCLUDE_FROM]

    return cmd


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------
def _run_cmd(cmd: list[str], logger: logging.Logger) -> int:
    logger.info("Running: %s", " ".join(cmd))
    start = time.monotonic()
    try:
        proc = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        for line in proc.stdout.splitlines():
            logger.info("[rclone] %s", line)
        elapsed = time.monotonic() - start
        logger.info("Exit code %d in %.1fs.", proc.returncode, elapsed)
        return proc.returncode
    except FileNotFoundError:
        logger.error("rclone executable not found: %s", cmd[0])
        return 127
    except Exception as exc:
        logger.error("Unexpected error running rclone: %s", exc)
        return 1


def _write_status(success: bool, message: str, details: dict) -> None:
    STATUS_FILE.write_text(
        json.dumps({{
            "job": JOB_NAME,
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "success": success,
            "message": message,
            **details,
        }}, indent=2),
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    ts  = datetime.now().strftime("%Y%m%d_%H%M%S")
    LOG_FOLDER.mkdir(parents=True, exist_ok=True)
    log_file = LOG_FOLDER / f"{{JOB_NAME}}_{{ts}}.log"
    logger   = _setup_logging(log_file)

    logger.info("=== Backup job starting: %s ===", JOB_NAME)

    # Preflight
    failures = _preflight(logger)
    if failures:
        for f in failures:
            logger.error("PREFLIGHT FAILED: %s", f)
        _write_status(False, "Preflight failed", {{"preflight_failures": failures}})
        return 2

    # Lock
    if not _acquire_lock(logger):
        _write_status(False, "Lock acquisition failed", {{}})
        return 3

    exit_code = 0
    all_results = []
    try:
        for src in SOURCE_FOLDERS:
            dest = f"{{RCLONE_DEST}}/{{Path(src).name}}" if len(SOURCE_FOLDERS) > 1 else RCLONE_DEST
            logger.info("--- Backing up: %s → %s ---", src, dest)

            attempt_rc = 1
            for attempt in range(1, RETRIES + 1):
                cmd = _build_rclone_cmd(src, dest)
                rc  = _run_cmd(cmd, logger)
                if rc == 0:
                    attempt_rc = 0
                    break
                logger.warning("Attempt %d/%d failed (exit %d). Waiting %ds...",
                               attempt, RETRIES, rc, RETRY_DELAY_SEC)
                if attempt < RETRIES:
                    time.sleep(RETRY_DELAY_SEC)

            all_results.append({{"source": src, "dest": dest, "exit_code": attempt_rc}})
            if attempt_rc != 0:
                exit_code = attempt_rc
                logger.error("Failed to back up %s after %d attempts.", src, RETRIES)

        # Post-copy validation
        if POST_VALIDATION and exit_code == 0:
            logger.info("--- Running post-copy validation ---")
            for res in all_results:
                check_cmd = [RCLONE_EXE, "check", res["source"], res["dest"],
                             f"--checkers={{CHECKERS}}"]
                check_rc = _run_cmd(check_cmd, logger)
                if check_rc != 0:
                    logger.error("Validation failed for %s", res["source"])
                    exit_code = check_rc

        success = exit_code == 0
        _write_status(success, "OK" if success else "FAILED",
                      {{"sources": all_results, "exit_code": exit_code}})

    finally:
        _release_lock()

    logger.info("=== Backup job finished: %s (exit %d) ===", JOB_NAME, exit_code)
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
'''

LAUNCHER_BAT_TEMPLATE = '''\
@echo off
:: Launcher for backup job: {job_name}
:: Generated by rclone Backup Configurator. Do not edit.
SET PYTHON={python_exe}
SET SCRIPT={script_path}
"%PYTHON%" "%SCRIPT%" %*
'''
