"""
tests/test_app.py — Unit tests for rclone Backup Configurator.

Generated by local-expert generate_tests (local model, no escalation).
Orchestrator corrections: fixed field names (remote_name/remote_path not
rclone_dest), fixed BackupMode/Frequency enum values, removed hallucinated
fields (BackupMode.INCREMENTAL does not exist), aligned JobConfig constructor
calls, and corrected error string assertions to match actual validation.py output.
"""
from __future__ import annotations

import shutil
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from generator import preview_rclone_command, render_script
from models import BackupMode, ExcludeConfig, Frequency, JobConfig, LogLevel, SchedulerConfig
from scheduler import build_task_command
from validation import validate_job


def _minimal_valid_config(tmp_src: Path) -> JobConfig:
    """Return a JobConfig that passes all validation (uses a real directory)."""
    return JobConfig(
        job_name     = "test_backup",
        source_folders = [tmp_src],
        remote_name  = "gdrive",
        remote_path  = "Backups/Test",
    )


class TestValidation(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())
        self.src = self.tmp / "source"
        self.src.mkdir()

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_empty_job_name_fails(self) -> None:
        cfg = _minimal_valid_config(self.src)
        cfg.job_name = ""
        result = validate_job(cfg)
        self.assertFalse(result.is_valid)
        self.assertTrue(any("name" in e.lower() for e in result.errors), result.errors)

    def test_valid_job_name_passes(self) -> None:
        cfg = _minimal_valid_config(self.src)
        result = validate_job(cfg)
        self.assertTrue(result.is_valid, result.errors)

    def test_unsafe_job_name_fails(self) -> None:
        cfg = _minimal_valid_config(self.src)
        cfg.job_name = "my job!!"
        result = validate_job(cfg)
        self.assertFalse(result.is_valid)

    def test_no_source_folders_fails(self) -> None:
        cfg = _minimal_valid_config(self.src)
        cfg.source_folders = []
        result = validate_job(cfg)
        self.assertFalse(result.is_valid)
        self.assertTrue(any("source" in e.lower() for e in result.errors), result.errors)

    def test_nonexistent_source_folder_fails(self) -> None:
        cfg = _minimal_valid_config(self.src)
        cfg.source_folders = [Path("/no/such/directory/xyz")]
        result = validate_job(cfg)
        self.assertFalse(result.is_valid)

    def test_bad_bwlimit_fails(self) -> None:
        cfg = _minimal_valid_config(self.src)
        cfg.bwlimit = "not-a-limit"
        result = validate_job(cfg)
        self.assertFalse(result.is_valid)
        self.assertTrue(any("bandwidth" in e.lower() or "bwlimit" in e.lower() for e in result.errors), result.errors)

    def test_valid_bwlimit_passes(self) -> None:
        for limit in ("50M", "1G", "500K", "2T", "100"):
            cfg = _minimal_valid_config(self.src)
            cfg.bwlimit = limit
            result = validate_job(cfg)
            self.assertTrue(result.is_valid, f"Expected valid for bwlimit={limit}: {result.errors}")

    def test_empty_remote_name_fails(self) -> None:
        cfg = _minimal_valid_config(self.src)
        cfg.remote_name = ""
        result = validate_job(cfg)
        self.assertFalse(result.is_valid)

    def test_remote_name_with_space_fails(self) -> None:
        cfg = _minimal_valid_config(self.src)
        cfg.remote_name = "my drive"
        result = validate_job(cfg)
        self.assertFalse(result.is_valid)


class TestGenerator(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())
        self.src = self.tmp / "source"
        self.src.mkdir()

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _cfg(self) -> JobConfig:
        return JobConfig(
            job_name       = "my_job",
            source_folders = [self.src],
            remote_name    = "gdrive",
            remote_path    = "Backups/Home",
        )

    def test_preview_contains_rclone_and_remote(self) -> None:
        cmd = preview_rclone_command(self._cfg())
        self.assertIn("rclone", cmd)
        self.assertIn("gdrive:Backups/Home", cmd)

    def test_preview_dry_run_mode(self) -> None:
        cfg = self._cfg()
        cfg.backup_mode = BackupMode.DRY_RUN
        cmd = preview_rclone_command(cfg)
        self.assertIn("--dry-run", cmd)

    def test_render_script_contains_key_variables(self) -> None:
        script = render_script(self._cfg())
        self.assertIn("JOB_NAME", script)
        self.assertIn("SOURCE_FOLDERS", script)
        self.assertIn("RCLONE_DEST", script)
        self.assertIn("my_job", script)
        self.assertIn("gdrive:Backups/Home", script)

    def test_render_script_contains_lock_and_retry(self) -> None:
        script = render_script(self._cfg())
        self.assertIn("LOCK_FILE", script)
        self.assertIn("RETRIES", script)


class TestScheduler(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())
        self.src = self.tmp / "source"
        self.src.mkdir()

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _cfg(self, freq: Frequency, time: str = "02:00", day: str = "Monday") -> JobConfig:
        cfg = JobConfig(
            job_name       = "sched_job",
            source_folders = [self.src],
            remote_name    = "gdrive",
            remote_path    = "Backups",
            scheduler      = SchedulerConfig(frequency=freq, trigger_time=time, day_of_week=day),
        )
        return cfg

    def test_daily_command_contains_trigger_time(self) -> None:
        text = build_task_command(self._cfg(Frequency.DAILY, time="03:30"), self.tmp)
        self.assertIn("03:30", text)

    def test_weekly_command_contains_day(self) -> None:
        text = build_task_command(self._cfg(Frequency.WEEKLY, day="Saturday"), self.tmp)
        self.assertIn("Saturday", text)

    def test_hourly_uses_repetition(self) -> None:
        text = build_task_command(self._cfg(Frequency.HOURLY), self.tmp)
        self.assertIn("HOURLY", text.upper())

    def test_output_contains_bat_path(self) -> None:
        text = build_task_command(self._cfg(Frequency.DAILY), self.tmp)
        self.assertIn("sched_job", text)


class TestModelRoundTrip(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = Path(tempfile.mkdtemp())
        self.src = self.tmp / "source"
        self.src.mkdir()

    def tearDown(self) -> None:
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _full_cfg(self) -> JobConfig:
        return JobConfig(
            job_name       = "roundtrip",
            source_folders = [self.src, self.tmp],
            remote_name    = "mydrive",
            remote_path    = "Backups/Test",
            backup_mode    = BackupMode.DRY_RUN,
            retries        = 5,
            bwlimit        = "20M",
            checksum       = True,
            excludes       = ExcludeConfig(patterns=["*.tmp", "*.log"]),
            scheduler      = SchedulerConfig(
                frequency    = Frequency.WEEKLY,
                trigger_time = "04:00",
                day_of_week  = "Friday",
            ),
        )

    def test_to_dict_from_dict_round_trip(self) -> None:
        original = self._full_cfg()
        restored = JobConfig.from_dict(original.to_dict())
        self.assertEqual(original.job_name, restored.job_name)
        self.assertEqual(original.backup_mode, restored.backup_mode)
        self.assertEqual(original.retries, restored.retries)
        self.assertEqual(original.bwlimit, restored.bwlimit)
        self.assertEqual(original.checksum, restored.checksum)
        self.assertEqual(original.excludes.patterns, restored.excludes.patterns)
        self.assertEqual(original.scheduler.frequency, restored.scheduler.frequency)
        self.assertEqual(original.scheduler.trigger_time, restored.scheduler.trigger_time)
        self.assertEqual(original.scheduler.day_of_week, restored.scheduler.day_of_week)

    def test_to_json_from_json_round_trip(self) -> None:
        original = self._full_cfg()
        restored = JobConfig.from_json(original.to_json())
        self.assertEqual(original.job_name, restored.job_name)
        self.assertEqual(original.remote_name, restored.remote_name)
        self.assertEqual(original.remote_path, restored.remote_path)
        self.assertEqual(len(original.source_folders), len(restored.source_folders))

    def test_backup_mode_enum_values(self) -> None:
        self.assertEqual(BackupMode.COPY.value,       "copy")
        self.assertEqual(BackupMode.DRY_RUN.value,    "dry_run")
        self.assertEqual(BackupMode.CHECK_ONLY.value,  "check_only")

    def test_frequency_enum_values(self) -> None:
        self.assertEqual(Frequency.MANUAL.value,  "manual")
        self.assertEqual(Frequency.DAILY.value,   "daily")
        self.assertEqual(Frequency.WEEKLY.value,  "weekly")
        self.assertEqual(Frequency.HOURLY.value,  "hourly")


if __name__ == "__main__":
    unittest.main()
